"""Derived, idempotent one-way mirror: promotable Hermes Ledger tickets → vault gotcha pages.

The Ledger is the source of truth (ADR 0002). The vault is a human-browsable mirror.
Re-running is byte-stable. Pages for tickets that are no longer promotable are pruned.
Human-authored pages (no ``generator: _mirror_learnings`` sentinel) are never touched.
"""
from __future__ import annotations

import json
import os
import re
import sys
import tempfile
from pathlib import Path
from typing import Any

import yaml

from _improvement import ledger_dir
from _learnings import is_gate_passed, _fmt_evidence
from _promotion import load_tickets, PromotionError

Ticket = dict[str, Any]

GENERATOR = "_mirror_learnings"


def load_promotable(ledger: Path) -> tuple[bool, list[Ticket]]:
    """Load gate-passed tickets and return an authoritative flag.

    Returns ``(authoritative, tickets)`` where:
    - ``(False, [])`` — ledger absent or not a directory; unknown state, do NOT prune.
    - ``(False, [...])`` — ledger loaded but one or more tickets failed to parse;
                           mirror the parseable promotable pages (writes are always safe)
                           but skip pruning (authoritative=False).
    - ``(True, [...])`` — every ticket parsed cleanly; list may be empty
                          (authoritative empty = legitimately nothing to mirror, prune allowed).
    - ``(False, [])`` — dir-level / unexpected I/O error; unknown state, do NOT prune.
    """
    if not ledger.exists() or not ledger.is_dir():
        return (False, [])
    try:
        # Strict load: raises PromotionError on the FIRST malformed ticket.
        tickets = load_tickets(ledger, partial=False)
        authoritative = True
    except PromotionError:
        # At least one ticket is corrupt → ledger state is untrustworthy for prune.
        # Still mirror parseable promotable pages (writes are safe); skip prune.
        tickets = load_tickets(ledger, partial=True)
        authoritative = False
    except Exception as exc:
        sys.stderr.write(f"_mirror_learnings: ledger load error: {exc}\n")
        return (False, [])
    passed = [t for t in tickets if is_gate_passed(t)]
    passed.sort(key=lambda t: str(t.get("fingerprint", "")))
    return (authoritative, passed)


def select_promotable(ledger: Path) -> list[Ticket]:
    """Load all gate-passed tickets from the ledger, sorted by fingerprint.

    Thin back-compat wrapper over ``load_promotable``.
    Returns ``[]`` when the ledger is absent, unloadable, or has no gate-passed
    tickets — callers that need the authoritative flag must use ``load_promotable``.
    """
    _, tickets = load_promotable(ledger)
    return tickets


def gotcha_filename(ticket: Ticket) -> str:
    """Return the deterministic filename for a ticket's gotcha page."""
    fp = str(ticket.get("fingerprint", ""))
    return f"gotcha-{fp}.md"


def _yaml_scalar(s: str) -> str:
    """Strip newlines/CRs that would inject arbitrary YAML keys."""
    return str(s).replace("\r", " ").replace("\n", " ").strip()


def render_gotcha(ticket: Ticket) -> str:
    """Render a deterministic markdown gotcha page for a promotable ticket.

    Uses only the ticket's own stable fields — no ``datetime.now()`` — so
    re-runs produce byte-identical output.  ``source_path``/``locator`` fields
    are deliberately omitted (ADR 0002 forbids leaking gitignored scratch paths).
    """
    fp = _yaml_scalar(str(ticket.get("fingerprint", "")))
    state = _yaml_scalar(str(ticket.get("state", "")))
    source = _yaml_scalar(str(ticket.get("source", "")))
    raw_asset = ticket.get("candidate_asset")
    candidate_asset = _yaml_scalar(str(raw_asset) if raw_asset is not None else "")
    distinct_runs = ticket.get("distinct_runs", 0)
    occurrences = ticket.get("occurrences", 0)
    first_seen = _yaml_scalar(str(ticket.get("first_seen", "")))
    last_seen = _yaml_scalar(str(ticket.get("last_seen", "")))
    pattern = str(ticket.get("pattern", "(no pattern)"))
    pattern_title = pattern[:80]

    evidence_md = _fmt_evidence(ticket)

    frontmatter = (
        "---\n"
        "type: gotcha\n"
        f"generator: {GENERATOR}\n"
        "derived: true\n"
        f"fingerprint: {fp}\n"
        f"state: {state}\n"
        f"source: {source}\n"
        f"candidate_asset: {candidate_asset}\n"
        f"distinct_runs: {distinct_runs}\n"
        f"occurrences: {occurrences}\n"
        f"first_seen: {first_seen}\n"
        f"last_seen: {last_seen}\n"
        "---\n"
    )

    body = (
        f"# Gotcha — {pattern_title}\n"
        "\n"
        "> Derived mirror of a promotable Hermes ledger ticket (machine-generated by"
        " `orchestrator.py improvements-mirror` — do not hand-edit; edits are overwritten)."
        " Ledger is SoT (ADR 0002).\n"
        "\n"
        f"- **Pattern:** {pattern}\n"
        f"- **Source:** {source}\n"
        f"- **Candidate asset:** {candidate_asset or '—'}\n"
        f"- **Distinct runs:** {distinct_runs}\n"
        f"- **Occurrences:** {occurrences}\n"
        "\n"
        f"**Ledger fingerprint:** `{fp}`\n"
        "\n"
        "## Evidence\n"
        "\n"
        f"{evidence_md}\n"
    )

    return frontmatter + "\n" + body


_OWNED_FILENAME_RE = re.compile(r"^gotcha-[a-f0-9]{64}\.md$")


def _is_owned_page(path: Path) -> bool:
    """Return True iff this file is exclusively machine-authored by this module.

    Requires BOTH:
    1. filename matches ``gotcha-<64 hex chars>.md`` (our deterministic naming), AND
    2. frontmatter ``generator`` value is EXACTLY ``_mirror_learnings``.

    Uses PyYAML ``safe_load`` so a multi-line plain scalar whose first line
    looks like ``generator: _mirror_learnings`` but has an indented continuation
    is parsed to a different string and correctly fails condition 2.
    """
    if not _OWNED_FILENAME_RE.match(path.name):
        return False
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return False
    if not text.startswith("---\n"):
        return False
    end = text.find("\n---\n", 4)
    if end == -1:
        return False
    frontmatter_block = text[4:end]
    try:
        data = yaml.safe_load(frontmatter_block)
        if not isinstance(data, dict):
            return False
        return data.get("generator") == GENERATOR
    except Exception:
        return False


def _atomic_write(path: Path, content: str) -> None:
    """Write ``content`` to ``path`` atomically via temp+rename (same dir)."""
    fd, tmp = tempfile.mkstemp(dir=path.parent, suffix=".md.tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(content)
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def resolve_vault(repo_root: Path) -> Path:
    """Resolve vault path using the standard precedence.

    Order: ``NBM_VAULT_PATH`` → ``VAULT_BUILDER_VAULT`` →
    ``${VB_OBSIDIAN_ROOT:-$HOME/Documents/Obsidian}/<basename(repo_root)>``.
    Mirrors ``hooks/session-distill-stop.sh`` resolution exactly.
    """
    vault_str = os.environ.get("NBM_VAULT_PATH") or os.environ.get("VAULT_BUILDER_VAULT") or ""
    if vault_str:
        return Path(vault_str)
    obsidian_root = Path(
        os.environ.get("VB_OBSIDIAN_ROOT")
        or str(Path.home() / "Documents" / "Obsidian")
    )
    return obsidian_root / repo_root.name


def mirror(
    ledger: Path,
    vault: Path,
    *,
    dry_run: bool = False,
) -> dict[str, int]:
    """Perform a true one-way sync: Ledger promotable tickets → vault/gotchas/.

    Returns counts: ``{"written": w, "unchanged": u, "pruned": p, "skipped_human": h}``.
    When ``dry_run`` is True, no disk writes occur.

    Prune safety: owned pages are only removed when the ledger load is
    authoritative (ledger present + every ticket parsed cleanly). An absent,
    unreadable, or partially-corrupt ledger is UNKNOWN state — pruning is
    skipped entirely so a misconfigured HOME, transient I/O error, or corrupt
    ticket file never silently wipes generated gotchas.
    """
    gotchas_dir = vault / "gotchas"

    # Load promotable tickets with explicit authoritative flag.
    authoritative, promotable_tickets = load_promotable(ledger)

    # Build desired state: filename → content
    desired: dict[str, str] = {
        gotcha_filename(t): render_gotcha(t)
        for t in promotable_tickets
    }

    # Discover existing owned pages (strict ownership check via _is_owned_page).
    # Also count any file in gotchas/ that is NOT owned by us (human pages).
    existing_owned: dict[str, Path] = {}
    skipped_human = 0
    if gotchas_dir.exists():
        for p in gotchas_dir.iterdir():
            if not p.is_file():
                continue
            if _is_owned_page(p):
                existing_owned[p.name] = p
            else:
                skipped_human += 1

    written = 0
    unchanged = 0
    pruned = 0

    if not dry_run:
        gotchas_dir.mkdir(parents=True, exist_ok=True)

    # Write or skip desired pages
    for filename, content in desired.items():
        dest = gotchas_dir / filename
        encoded = content.encode("utf-8")
        if dest.exists() and dest.read_bytes() == encoded:
            unchanged += 1
        else:
            if not dry_run:
                _atomic_write(dest, content)
            written += 1

    # Prune owned pages not in desired — ONLY when the ledger load was authoritative.
    # Non-authoritative (absent/unreadable ledger) → skip pruning entirely.
    if authoritative:
        for filename, path in existing_owned.items():
            if filename not in desired:
                if not dry_run:
                    path.unlink(missing_ok=True)
                pruned += 1

    return {"written": written, "unchanged": unchanged, "pruned": pruned,
            "skipped_human": skipped_human}


def register_cli_subparsers(sub: Any) -> None:
    """Register ``improvements-mirror`` onto the orchestrator CLI parser."""
    p_im = sub.add_parser("improvements-mirror")
    p_im.add_argument("--repo-root", default=".", dest="repo_root")
    p_im.add_argument("--vault", default=None, dest="vault",
                      help="explicit vault path override (default: resolve_vault)")
    p_im.add_argument("--dry-run", action="store_true", dest="dry_run")
    p_im.set_defaults(func=cmd_improvements_mirror)


def cmd_improvements_mirror(args: Any) -> int:
    """CLI handler: mirror promotable tickets to the vault gotchas directory."""
    repo_root = Path(getattr(args, "repo_root", ".")).resolve()
    ledger = ledger_dir(repo_root, None)
    vault_arg = getattr(args, "vault", None)
    vault = Path(vault_arg) if vault_arg else resolve_vault(repo_root)
    dry_run = bool(getattr(args, "dry_run", False))

    counts = mirror(ledger, vault, dry_run=dry_run)
    print(json.dumps(counts))
    return 0
